### ISSUE TITLE
Set `build_locally` in a partition in the configuration

### ISSUE THREAD

**Issue by ekouts** [reframe-hpc/reframe#2989] opened 2023-09-07 09:55 UTC
There are partitions that we will always have to build remotely so it would be useful to be able to set in the configuration, instead of always passing it through the cli or setting it in the test.

**Comment by vkarak** [comment] 2023-09-07 10:56
This is also related to #1500.

**Comment by giordano** [comment] 2023-10-05 12:20
I was going to open a ticket about this very same feature request :slightly_smiling_face:

**Comment by vkarak** [comment] 2024-02-07 22:49
Closing as duplicate of #2259.

**Closed by vkarak** 2024-02-07 22:49 UTC
Labels: new feature, prio: normal, configuration
