### ISSUE TITLE
`perflogs` not created when using `sn.make_performance_function`

### ISSUE THREAD

**Issue by jack-morrison** [reframe-hpc/reframe#2728] opened 2023-01-09 18:35 UTC
I'm opening this issue following [this discussion](https://reframetalk.slack.com/archives/CF8ENLUDB/p1673282910756139) in the ReFrame Slack.

After migrating to 4.x, I find that my test's exclusive use of `sn.make_performance_function` (no use of the `@performance_function` decorator) causes the `perflogs` directory not to be created, and yields no performance log files following the successful run of a performance test.

**Comment by vkarak** [comment] 2023-01-19 09:26
I can confirm this behaviour; it's certainly a bug.

**Comment by vkarak** [comment] 2023-01-19 09:37
At the moment, you can workaround this if you don't set the `perf_variables` in pre-performance hook, but rather in an after sanity hook. The reason is that reframe checks if a test is a performance test and enables the performance logger just before it enters the performance stage. If you set the `perf_variables` during the performance stage (the logical thing), at the moment of the check, they are still empty and reframe would think that this is not a performance test. Another workaround would be to fill `perf_variables` with some dummy data at the beginning.

**Comment by vkarak** [comment] 2023-01-27 18:14
Merged into develop.

**Closed by vkarak** 2023-01-27 18:14 UTC
Labels: bug, prio: normal
